### ISSUE TITLE
スライドURLを設定したあと発表者のみ1枚目のスライドが表示されない

### ISSUE THREAD

**Issue by KOBA789** [vrc-lt/SlidePlayer#1]
OnURLChanged 内において、`_page`, `localPage` の更新はするものの、

https://github.com/vrc-lt/SlidePlayer/blob/7a5fa00bb79a7b6d2436ad065138381e31e87ed0/script/SlidePlayer.cs#L44-L45

その後の `OnDeserialization`内、 `OnVideoReady` 内いずれにおいても `Networking.IsOwner()` が `true` となることから `ChangeVideoPosition` が呼ばれるチャンスがない。

https://github.com/vrc-lt/SlidePlayer/blob/7a5fa00bb79a7b6d2436ad065138381e31e87ed0/script/SlidePlayer.cs#L97
https://github.com/vrc-lt/SlidePlayer/blob/7a5fa00bb79a7b6d2436ad065138381e31e87ed0/script/SlidePlayer.cs#L119

**Comment by haru2036** [comment]
@KOBA789 Issueを立てていただいてありがとうございます！
ビデオが読み込まれたあとでないと`ChangeVideoPosition`しても画面は更新されなさそうだったので、`OnVideoReady`ではOwnerかどうかに関わらず`ChangeVideoPosition`を呼ぶようにしてみました。
手元で試したときにはうまく言っているように見えたので、このリポジトリにマージしたらこのIssueはCloseしようと思います（このあたりの運用が全く固まっておらず申し訳ないです……）

**Comment by haru2036** [comment]
#2 で修正しました。ありがとうございます！
